#Typical values: lts, preview, 7.1.3, 7.2.0-preview.5
#See: https://hub.docker.com/_/microsoft-powershell
ARG PWSHVERSION=lts
FROM mcr.microsoft.com/powershell:${PWSHVERSION}-ubuntu-18.04

LABEL description="Powershell Universal"
SHELL ["pwsh", "-noninteractive", "-command"]

#Path to Powershell Universal
ARG PSUPATH=/home/Universal
ARG PSUDATAPATH=/data

#Specify latest to get the latest version or a specific version (e.g. 1.5.16) if otherwise
ARG PSUVERSION=latest
ARG PSUMODULEVERSION=$PSUVERSION

RUN apt update && apt install -y git && apt clean;
RUN $ErrorActionPreference='Stop'; $ProgressPreference = 'silentlyContinue';\
    [hashtable]$imParams = if ($env:PSUMODULEVERSION -and $env:PSUMODULEVERSION -ne 'latest') { @{RequiredVersion = $env:PSUMODULEVERSION} } else {@{}}; \
    "Installing Universal Module " + $env:PSUMODULEVERSION; \
    Install-Module @imParams -Name Universal -Force; \
    [hashtable]$psuParams = if ($env:PSUVERSION -and $env:PSUVERSION -ne 'latest') { @{Version = $env:PSUVERSION}} else {@{}}; \
    "Installing Powershell Universal " + $env:PSUMODULEVERSION; \
    Install-PSUServer @psuParams -Path $env:PSUPATH; \
    chmod +x $env:PSUPATH/Universal.Server; \
    New-Item -ItemType Directory $env:PSUDATAPATH; \
    usermod --shell /usr/bin/pwsh root;

ENV Data__RepositoryPath=$PSUDATAPATH/Repository
ENV Data__ConnectionString=$PSUDATAPATH/database.db
ENV UniversalDashboard__AssetsFolder=$PSUDATAPATH/UniversalDashboard 
ENV Logging__Path=$PSUDATAPATH/logs/log.txt

#Default entry point: Start Server
ENTRYPOINT ["/home/Universal/Universal.Server"]

EXPOSE 5000