FROM mcr.microsoft.com/powershell:latest
WORKDIR /app

# Note: The DEBIAN_FRONTEND export avoids warnings when you go on to work with your container.
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install git

# Install dotnet
RUN apt-get install -y dotnet-sdk-8.0

# Install dotnet-gitversion
RUN dotnet tool install --global GitVersion.Tool --version 5.*
RUN export PATH="$PATH:/root/.dotnet/tools"

# Switch to Powershell Shell
SHELL ["/usr/bin/pwsh", "-c"]

# Install Powershell Modules
RUN $ErrorActionPreference='Stop'; Install-Module -Name Pester, InvokeBuild, ModuleBuilder, PlatyPS, PSScriptAnalyzer -Force

# Import Powershell profile
# Profile is stored in a gist here
# https://api.github.com/gists/6fcbb253abcfec1df62bfc38667738f7
RUN $ErrorActionPreference='Stop';if (!(Test-Path -Path $PROFILE)) { New-Item -ItemType File -Path $PROFILE -Force }; $gist = Invoke-RestMethod "https://api.github.com/gists/6fcbb253abcfec1df62bfc38667738f7" -ErrorAction Stop; $gistProfile = $gist.Files.'profile.ps1'.Content; Set-Content -Path $profile.CurrentUserAllHosts -Value $gistProfile

# Clone repo
RUN git clone git@github.com:douda/PSSymantecSEPM.git

WORKDIR /app/PSSymantecSEPM

CMD [ "pwsh" ]
