FROM mcr.microsoft.com/powershell:latest

# Note: The DEBIAN_FRONTEND export avoids warnings when you go on to work with your container.
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install git

# Install dotnet
RUN apt-get install -y dotnet-sdk-8.0

# Install dotnet-gitversion
RUN dotnet tool install --global GitVersion.Tool --version 5.*
RUN export PATH="$PATH:/root/.dotnet/tools"

# Install Powershell Modules
SHELL ["/usr/bin/pwsh", "-c"]
RUN $ErrorActionPreference='Stop'; Install-Module -Name Pester, InvokeBuild, ModuleBuilder, PlatyPS, PSScriptAnalyzer -Force

# Build and load the module
SHELL ["/usr/bin/pwsh", "-c"]
RUN ./__For_Dev_And_Maintenance/Build_and_load_module.ps1

CMD [ "pwsh" ]
